name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build:
    name: Build
    uses: ./.github/workflows/build-module.yml
