name: Build Module

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.26']
        goos: [linux, darwin, windows, freebsd]
        goarch: [amd64, arm64]
        exclude:
          - goos: freebsd
            goarch: arm64
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: go mod download
    - run: go mod verify
    - run: go build -v ./...
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
